# Generated by Django 2.2.3 on 2020-10-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default=None, max_length=200)),
                ('title_jp', models.CharField(blank=True, default=None, max_length=200)),
                ('img_url', models.ImageField(blank=True, default=None, upload_to='pokemons')),
                ('description', models.TextField(blank=True, default=None)),
                ('previous_evolution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Lat')),
                ('longitude', models.FloatField(verbose_name='Lon')),
                ('appeared_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('disappeared_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('level', models.IntegerField(blank=True, default=None, null=True)),
                ('health', models.IntegerField(blank=True, default=None, null=True)),
                ('strongth', models.IntegerField(blank=True, default=None, null=True)),
                ('defence', models.IntegerField(blank=True, default=None, null=True)),
                ('stamina', models.IntegerField(blank=True, default=None, null=True)),
                ('pokemon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
