# Generated by Django 3.1.1 on 2020-10-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20201011_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_id',
            new_name='id',
        ),
    ]
