# Generated by Django 3.1.1 on 2020-10-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20201022_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='elements', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
    ]
