# Generated by Django 3.1.1 on 2020-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20201029_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
