# Generated by Django 2.2.3 on 2020-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20201029_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='img_url',
            field=models.ImageField(blank=True, default=None, upload_to='elements', verbose_name='Изображение'),
        ),
    ]
