# Generated by Django 2.2.3 on 2020-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20201114_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='strong_against',
        ),
    ]
