# Generated by Django 2.2.3 on 2020-11-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='strong_against',
        ),
    ]
